name: GitHub Release

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  release:
    name: Release native binaries
    permissions:
      id-token: write
      attestations: write
      artifact-metadata: write
      contents: write
    strategy:
      matrix:
        kind: [ 'linux-amd64', 'linux-arm64', 'macos-amd64', 'macos-arm64', 'windows-amd64', 'windows-arm64' ]
        include:
          - kind: linux-amd64
            os: ubuntu-latest
            target: linux-x64
          - kind: linux-arm64
            os: ubuntu-24.04-arm
            target: linux-arm64
          - kind: macos-amd64
            os: macos-15-intel
            target: osx-x64
          - kind: macos-arm64
            os: macos-latest
            target: osx-arm64
          - kind: windows-amd64
            os: windows-latest
            target: win-x64
          - kind: windows-arm64
            os: windows-11-arm
            target: win-arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup dotnet
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: 10.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'

      - name: Prepare driver.json
        shell: bash
        run: .github/scripts/prepare-driver-json.sh

      - name: Build
        shell: bash
        run: |
          # Build everything
          release_name="unfolded-circle-oppo-$DRIVER_TAG-${{ matrix.kind }}"

          dotnet restore "./src/UnfoldedCircle.OppoBluRay/UnfoldedCircle.OppoBluRay.csproj" --locked-mode -p:PublishAot=true
          dotnet publish "./src/UnfoldedCircle.OppoBluRay/UnfoldedCircle.OppoBluRay.csproj" -r ${{ matrix.target }} -c Release -o ./publish -p:Version="$DRIVER_VERSION" -p:PublishAot=true --no-restore
          if [ "${{ matrix.target }}" == "linux-arm64" ]; then
            mkdir driverdir && mkdir driverdir/bin && mkdir driverdir/config && mkdir driverdir/data
            cp publish/driver.json driverdir/driver.json
            cp ./oppo.png ./driverdir/oppo.png
            cp publish/appsettings.json driverdir/config/

            cp publish/driver driverdir/bin/
            cp publish/driver.dbg driverdir/bin/

            tar -czvf unfolded-circle-oppo-$DRIVER_TAG-remote.tar.gz -C ./driverdir .

            # Delete output directory
            rm -r "./driverdir"
          fi

          if [ "${{ matrix.kind }}" = "windows-amd64" ] || [ "${{ matrix.kind }}" = "windows-arm64" ]; then
            # Pack to zip for Windows
            7z a -tzip "${release_name}.zip" "./publish/*"
          else
            # Pack tar.gz for non-Windows
            tar -czvf "${release_name}.tar.gz" -C ./publish .
          fi

          # Delete output directory
          rm -r "./publish"

      - name: Publish
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: |
            unfolded-circle-oppo*.zip
            unfolded-circle-oppo*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest build provenance
        uses: actions/attest@f7c74d28b9d84cb8768d0b8ca14a4bac6ef463e6 # v4.2.0
        with:
          subject-path: |
            unfolded-circle-oppo*.tar.gz
            unfolded-circle-oppo*.zip
